  parameters:
  - name: ArtifactName
    type: string
    default: Products
  - name: ApplicationName
    type: string
    default: Products
  - name: ApplicationDisplayName
    type: string
    default: Products
  - name: TemplateDirectory
    type: string
    default: bicep
  - name: ProjectsToDeploy
    type: object
    default: []

  trigger:
    branches:
      include:
      - main
    paths:
      include:
      - bicep/**
  
  pool:
    vmImage: ubuntu-latest
  
  stages:
  - stage: "Build"
    jobs:
      - job: Build
        displayName: "Build"
        steps:
          - template: bicep/pipeline-bicep-build.yaml
            parameters:
              TemplateDirectory: ${{ parameters.TemplateDirectory }}
              SubscriptionName: ''
              SubscriptionId: ''
  - ${{ if ne(variables['Build.Reason'], 'PullRequest') }}:
    - template: pipeline-release.yaml
      parameters:
        Stage: Dev
        SubscriptionName: ''
        SubscriptionId: ''
        ArtifactName: ${{ parameters.ArtifactName }}
        ApplicationDisplayName: ${{ parameters.ApplicationDisplayName }}
        ProjectsToDeploy: ${{ parameters.ProjectsToDeploy }}
        VnetName: 'vnet-apimdemo-dev'
  - ${{ if and(ne(variables['Build.Reason'], 'PullRequest'), eq(variables['Build.SourceBranch'], 'refs/heads/main')) }}:
    - template: pipeline-release.yaml
      parameters:
        Stage: Test
        SubscriptionName: ''
        SubscriptionId: ''
        ArtifactName: ${{ parameters.ArtifactName }}
        ApplicationDisplayName: ${{ parameters.ApplicationDisplayName }}
        ProjectsToDeploy: ${{ parameters.ProjectsToDeploy }}
        VnetName: 'vnet-apimdemo-tst'