parameters:
  - name: Stage
    type: string
  - name: SubscriptionName
    type: string
  - name: SubscriptionId
    type: string
  - name: ApplicationDisplayName
    type: string
  - name: PostBicepSteps
    type: stepList
    default: []
  - name: Location
    type: string
    default: westeurope
  - name: VnetName
    type: string
    default: ''
  - name: BicepParamOverrides
    type: string
    default: ''

jobs:
- deployment: Bicep
  displayName: "Apply Bicep"
  environment:
    name: ${{ parameters.ApplicationDisplayName }} ${{ lower(parameters.Stage) }}
  strategy:
    runOnce:
      deploy:
        steps:
          - download: none
          - task: DownloadBuildArtifacts@0
            displayName: Download Bicep template and parameters
            inputs:
              buildType: 'current'
              downloadType: 'single'
              artifactName: 'Bicep'
              downloadPath: '$(System.ArtifactsDirectory)'

          - ${{ if ne(parameters.VnetName, '') }}:
            - task: AzureCLI@2
              displayName: 'Fetch VNet status'
              inputs:
                azureSubscription: ${{ parameters.SubscriptionName }}
                scriptType: 'pscore'
                scriptLocation: 'inlineScript'
                inlineScript: |
                  $vnetName = $env:VNET_NAME
                  $result = az network vnet list --query "[?name=='$vnetName'] | length(@)"
                  Write-Host "##vso[task.setvariable variable=VNetExistsResult;]$result"
              env:
                VNET_NAME: ${{ parameters.VnetName }}

          - task: AzureResourceManagerTemplateDeployment@3
            name: deployBicep
            displayName: 'Deploy resources in Azure'
            inputs:
              deploymentScope: 'Subscription'
              azureResourceManagerConnection: '${{ parameters.SubscriptionName }}'
              subscriptionId: '${{ parameters.SubscriptionId }}'
              location: '${{ parameters.Location }}'
              templateLocation: 'Linked artifact'
              csmFile: '$(System.ArtifactsDirectory)/Bicep/templates/main.json'
              csmParametersFile: '$(System.ArtifactsDirectory)/Bicep/templates/parameters/parameters.${{ lower(parameters.Stage) }}.json'
              ${{ if and(ne(variables['VNetExistsResult'], ''), ne(parameters.BicepParamOverrides, '')) }}:
                overrideParameters: ${{ parameters.BicepParamOverrides }} -vnetExistsResult $(VNetExistsResult)
              ${{ elseif and(eq(variables['VNetExistsResult'], ''), ne(parameters.BicepParamOverrides, '')) }}:
                overrideParameters: ${{ parameters.BicepParamOverrides }}
              ${{ elseif and(ne(variables['VNetExistsResult'], ''), eq(parameters.BicepParamOverrides, '')) }}:
                overrideParameters: -vnetExistsResult $(VNetExistsResult)
              deploymentMode: 'Incremental'
              deploymentOutputs: 'deploymentOutput'

          - task: PowerShell@2
            displayName: "Persist Bicep output across jobs"
            name: bicepOutput
            inputs:
              targetType: inline
              pwsh: true
              script: Write-Host '##vso[task.setvariable variable=deploymentOutput;isoutput=true]$(deploymentOutput)'

          - ${{ parameters.PostBicepSteps }}